apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80  
        volumeMounts: # pod path
        - name: myhostpath # use
          mountPath: /usr/share/nginx/html
      volumes: # worker node path
      - name: myhostpath # create
        hostPath:    
          path: /home/ubuntu/bkp # created inside EBS of worker node
          type: DirectoryOrCreate