## Replication Controller file -> it doesn't support conditons
apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3 # it helps to create 3 pods
  selector: # it helps to adopt the pod on the basis of label
    app: myapp
  template: # it helps to create a pod on the basis of configuration of  metadata 
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80